---
title: 'Chapter 5: Comparisons Among Several Samples'
author: "Loren"
date: "08/26/2014"
output:
   knitrBootstrap::bootstrap_document:
        title: "Chapter 5: Comparisons Among Several Samples"
        theme: default
        highlight: xcode
        theme.chooser: TRUE
        highlight.chooser: TRUE
---

```{r bootstrap.show.code=FALSE, bootstrap.show.message=FALSE}
library(knitr)
opts_chunk$set(bootstrap.show.code=FALSE, bootstrap.thumbnail=FALSE, bootstrap.show.message=FALSE)
library(ggplot2)
theme_set(new = theme_minimal())
library(plyr)
# upper-case column names annoy me
sleuth.read <- function(x) {
   d <- read.csv(x)
   names(d) <- tolower(names(d))
   d
}
```

# Chapter 5: Comparisons among several samples

# Examples

## Mice Diet and Longevity

```{r}
c0501 <- sleuth.read('ascii/case0501.csv')
```


## The Spock Trial

```{r}
c0502 <- sleuth.read('ascii/case0502.csv')
```

```{r}
require(ggplot2)
qplot(judge, percent, data=c0502, geom='boxplot')
table(c0502$judge)
```


Some models:

```{r}
full <- aov(percent ~ judge, c0502)
midway <- aov(percent ~ judge == "SPOCK'S", c0502)
reduced <- aov(percent ~ 1, c0502)
(test1 <- anova(full, reduced))
(test2 <- anova(midway, reduced)) # Significant at 1.03e-6
t.test(percent ~ (judge == "SPOCK'S"), c0502) # same p-value
```


A permutation test showing what the F-test means:

```{r}
n <- 100
f.stats <- numeric(n)
my.fun <- function(x) { sum((x - mean(x))^2) }
sst <- my.fun(c0502$percent)           # total sum of squared resids
dft <- nrow(c0502) - 1                 # total degrees of freedom
dfb <- length(levels(c0502$judge)) - 1 # df between groups
dfw <- dft - dfb                       # df within groups
for (i in 1:n) {
   ssw <- sum(with(c0502, tapply(sample(percent), judge, my.fun)))
   msw <- ssw / dfw # mean squared resid, within groups
   msb <- (sst - ssw) / dfb
   f.stats[i] <- msb / msw
}
hist(f.stats, freq=F)
x <- seq(from=0,to=6,by=0.01)
y <- df(x,6,39)
lines(x,y)
```


Let me look more closely at the between/within sum of squares...

```{r}
my.fun <- function(x) { sum((x - mean(x))^2) }
sst <- my.fun(c0502$percent)
df.total <- nrow(c0502) - 1
df.between <- length(levels(c0502$judge)) - 1
df.within <- df.total - df.between
ssw <- sum(with(c0502, tapply(percent, judge, my.fun))) # SS within groups

grand.mean <- mean(c0502$percent)
group.means <- with(c0502, tapply(percent, judge, mean))
group.sizes <- with(c0502, tapply(percent, judge, length))
group.resids <- group.means - grand.mean

# the same:
sst - ssw
weighted.mean((group.means - grand.mean)^2, group.sizes) * nrow(c0502)
```


## Diagnostics using Residuals

```{r}
c0501.full <- aov(lifetime ~ diet, data=c0501)
par(mfrow=c(2,2))
plot(c0501.full) # not sure how to get separate plots
df <- data.frame(estimated.means=c0501.full$fitted.values,
                 residuals=c0501.full$residuals)
```

Plotting means vs residuals:

```{r}
ggplot(df, aes(estimated.means, residuals)) +
   geom_point() + xlab('Estimated Mean Lifetime (months)') +
   ylab('Residual Lifetime (months)') +
   geom_hline(yintercept=0)
```



## Conceptual Exercises

1. 
2. 
3. 
